### ISSUE TITLE
Will kapre supports istft?

### ISSUE THREAD

**Issue by diggerdu** [keunwoochoi/kapre#1]

**Comment by keunwoochoi** [comment]
It's planned but not sure when. Theano has rfft and irfft (http://deeplearning.net/software/theano/library/tensor/fft.html), tensorflow has [fft](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard0/tf.fft.md) and [ifft](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard7/tf.ifft.md), so I wanna make a keras backend first to do so. 

I'll keep this issue open.

**Comment by diggerdu** [comment]
But doing ft through convolution will be every slow....
`https://en.wikipedia.org/wiki/Fast_Fourier_transform`

**Comment by diggerdu** [comment]
But implement FT using convolution is not the best method.
[https://en.wikipedia.org/wiki/Fast_Fourier_transform](fast fourier transform)

**Comment by diggerdu** [comment]
But implement FT using convolution is not the best method.
https://en.wikipedia.org/wiki/Fast_Fourier_transform

**Comment by keunwoochoi** [comment]
I know. Please read my first comment again. Let me know if there's rfft in tensorflow. 

+ One good thing of the current version: you can make it trainable. So I'll keep both later - keep Spectrogram and add something like STFT or RFFT.

**Comment by keunwoochoi** [comment]
Looked up a bit more. fft in tensorflow does not work on cpu. it requires `complex64` data type input. A viable way is to implement it only on theano with my own backend, but not sure if it's worth.

**Comment by keunwoochoi** [comment]
Just added a Theano-based [stft](https://github.com/keunwoochoi/kapre/blob/dev/kapre/stft.py). Seems like it's working.
@diggerdu Would you be interested to test it?

**Comment by keunwoochoi** [comment]
Stft implemention needs some fix. It doesn't pass `assert_allclose` with librosa result.

**Comment by diggerdu** [comment]
Thanks for your reply. I have imply STFT using skcuda, but it's slightly slower than librosa, the cost of communication between CPU and GPU are too expensive.
https://github.com/diggerdu/Karajan/blob/master/karajan/stft_cufft.py

**Comment by keunwoochoi** [comment]
Thanks! Good to know that.

**Comment by keunwoochoi** [comment]
We got fft-based stft now at https://github.com/keunwoochoi/kapre/blob/master/kapre/stft.py

**Comment by crosofg** [comment]
Has anyone built InverseSpectogram for kapre?

**Comment by keunwoochoi** [comment]
@crosofg  No, but I will do it.

**Comment by keunwoochoi** [comment]
Whoa, I have to change my plan. STFT might not be implemented. In ver 0.1, I removed it out since it even takes longer time -- perhaps because slicing the audio file into frames takes so long.
