### ISSUE TITLE
Melspectrogram for 'labels'

### ISSUE THREAD

**Issue by shash4897** [keunwoochoi/kapre#107]
Hi Keunwoochoi. Not exactly an issue, but I am attempting to do audio source separation using the audio mix as input and the stem as output. Since the output audio signals are so large (44100 samples per sec) it would be difficult apply a dense regression in the final layer with so many activation units. Is there anyway I can use the Melspectrogram layer on both the input and output and incorporate it within the model itself?

**Comment by keunwoochoi** [comment]
Technically it's possible to use melspectrograms. But afaik STFT is a much more popular choice. https://source-separation.github.io/tutorial/landing.html This tutorial can be helpful.

**Comment by shash4897** [comment]
Thanks! I will check this out.
