### ISSUE TITLE
Most direct replacement for Spectrogram

### ISSUE THREAD

**Issue by mo-seph** [keunwoochoi/kapre#114]
What's the most direct replacement in 0.3.x for the Spectrogram class from 0.1.7? I'm guessing it's `kapre.composed.get_stft_magnitude_layer` and then decomposing if I want to save in h5?

Thanks!

**Comment by keunwoochoi** [comment]
You're correct, that would be the best approximation. There are two difference though. 1) The old `Spectrogram` layer has a little more error than I expected compared to librosa and I couldn't figure out. 2) `Specrogram` used conv1d based DFT kernels while the current implementation uses `tf.signal.stft` which is based on FFT.

**Comment by mo-seph** [comment]
Great, thanks!
