### ISSUE TITLE
stft.py error

### ISSUE THREAD

**Issue by rajb245** [keunwoochoi/kapre#13]
There seems to be a mix up between the variable names "n_dft" and "n_fft". For example, in __init__ for the class, the argument is clearly n_fft, but the code that triggers when "n_hop" is undefined references "n_dft" which is not defined in this constructor. Similar problems are present in the documentation, it references "n_dft", but the constructor clearly uses "n_fft".

**Comment by keunwoochoi** [comment]
Hi, you're right. I realised it and actually I am going to remove it, stft is not any faster than just spectrogram. Probably because it is not done in parallel. You can check out 0.1 development branch.

**Comment by keunwoochoi** [comment]
Now things are resolved.
