### ISSUE TITLE
using np.max in decibel layers

### ISSUE THREAD

**Issue by jrmylee** [keunwoochoi/kapre#136]
Hello!  I'm training my model on decibel-scaled spectrograms and tried it once using Librosa to preprocess my audio, and another time using Kapre layers to directly feed audio without the preprocessing step.  I am having worse performance on my Kapre model, and the only real difference between them is that the Mag -> Decibel step is scaled using np.max in the librosa side, where as in Kapre it is set to 1.  I had a few questions:

1. Is it possible to plot Kapre magnitude STFTs using Librosa.display on the same scale as when using the Librosa power_to_db(..., ref=np.max)?
2. What is the purpose of using np.max as the reference value, and why might my model do better when using this data format?  
3. Is it possible to match the decibel data scale in Kapre as in Librosa?

Here are the Kapre layers I am using:

`self.STFT_Layer = STFT(n_fft=2048, win_length=2048, hop_length=512,
               window_name=None, pad_end=False, pad_begin=True,
               input_data_format='channels_last', output_data_format='channels_last',
               input_shape=(2048 * 22, 1))
        self.ISTFT_Layer = InverseSTFT(n_fft=2048, hop_length=512, 
                input_shape=(88, 1024, 1))
        self.Mag_Layer = Magnitude()
        self.Phase_layer = Phase()
        self.Decibel_Layer = MagnitudeToDecibel()`

Here are corresponding librosa functions:

`
x = librosa.util.normalize(x)
  stft = librosa.stft(x)
  db = librosa.amplitude_to_db(np.abs(stft), ref=np.max)
`

**Comment by jrmylee** [comment]
Don't know why I didn't think of this, but finally thought to create MagnitudeToDecibel layers on the fly with a unique max value for the spectrogram each time... :D

**Comment by keunwoochoi** [comment]
Oops I forgot to answer, sorry about it. Glad you figure it out :)
