### ISSUE TITLE
Melspectrogram() no arguments 'border_mode' or 'power'

### ISSUE THREAD

**Issue by NumesSanguis** [keunwoochoi/kapre#17]
I just copied your Mel-spectogram code found in the readme:

    # Keras model setup
    input_shape = (6, 44100)
    sr = 44100
    model = Sequential()
    # A mel-spectrogram layer
    model.add(Melspectrogram(n_dft=512, n_hop=256, input_shape=input_shape,
                             sr=sr, n_mels=128,
                             fmin=0.0, fmax=sr/2, power=1.0,
                             return_decibel_melgram=False, trainable_fb=False,
                             trainable_kernel=False,
                             name='trainable_stft'))

, but that gave the below 2 errors.
If I would delete these 2 arguments, the .add() doesn't give any error.

# 'border_mode'

    TypeError                                 Traceback (most recent call last)
    <ipython-input-10-41496f793cdb> in <module>()
          9                          return_decibel_melgram=False, trainable_fb=False,
         10                          trainable_kernel=False,
    ---> 11                          name='trainable_stft'))

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/kapre-0.1.2.1-py3.6.egg/kapre/time_frequency.py in __init__(self, sr, n_mels, fmin, fmax, power_melgram, return_decibel_melgram, trainable_fb, **kwargs)
        254                  trainable_fb=False, **kwargs):
        255 
    --> 256         super(Melspectrogram, self).__init__(**kwargs)
        257         assert sr > 0
        258         assert fmin >= 0.0

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/kapre-0.1.2.1-py3.6.egg/kapre/time_frequency.py in __init__(self, n_dft, n_hop, padding, power_spectrogram, return_decibel_spectrogram, trainable_kernel, image_data_format, **kwargs)
         96         self.power_spectrogram = float(power_spectrogram)
         97         self.return_decibel_spectrogram = return_decibel_spectrogram
    ---> 98         super(Spectrogram, self).__init__(**kwargs)
         99 
        100     def build(self, input_shape):

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/keras/engine/topology.py in __init__(self, **kwargs)
        277         for kwarg in kwargs:
        278             if kwarg not in allowed_kwargs:
    --> 279                 raise TypeError('Keyword argument not understood:', kwarg)
        280         name = kwargs.get('name')
        281         if not name:

    TypeError: ('Keyword argument not understood:', 'border_mode')

# 'power'

    TypeError                                 Traceback (most recent call last)
    <ipython-input-11-0ae5a30e071e> in <module>()
          9                          return_decibel_melgram=False, trainable_fb=False,
         10                          trainable_kernel=False,
    ---> 11                          name='trainable_stft'))
         12 
         13 # border_mode='same',

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/kapre-0.1.2.1-py3.6.egg/kapre/time_frequency.py in __init__(self, sr, n_mels, fmin, fmax, power_melgram, return_decibel_melgram, trainable_fb, **kwargs)
        254                  trainable_fb=False, **kwargs):
        255 
    --> 256         super(Melspectrogram, self).__init__(**kwargs)
        257         assert sr > 0
        258         assert fmin >= 0.0

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/kapre-0.1.2.1-py3.6.egg/kapre/time_frequency.py in __init__(self, n_dft, n_hop, padding, power_spectrogram, return_decibel_spectrogram, trainable_kernel, image_data_format, **kwargs)
         96         self.power_spectrogram = float(power_spectrogram)
         97         self.return_decibel_spectrogram = return_decibel_spectrogram
    ---> 98         super(Spectrogram, self).__init__(**kwargs)
         99 
        100     def build(self, input_shape):

    ~/anaconda3/envs/StoAU/lib/python3.6/site-packages/keras/engine/topology.py in __init__(self, **kwargs)
        277         for kwarg in kwargs:
        278             if kwarg not in allowed_kwargs:
    --> 279                 raise TypeError('Keyword argument not understood:', kwarg)
        280         name = kwargs.get('name')
        281         if not name:

    TypeError: ('Keyword argument not understood:', 'power')

**Comment by keunwoochoi** [comment]
`power` --> `power_melgram`, `border_mode` --> `padding` would work. I updated the readme. Thanks!
