### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by keunwoochoi** [keunwoochoi/kapre#18]
* #16 : make all the normalization would be done per sample.
* perhaps add phase computation in STFT (it's not the most efficient though)
* perhaps I can deprecate the support for theano

**Comment by lvaleriu** [comment]
Could you please try to keep theano? And even support CNTK backend (which is supported by keras) since it is faster and more precise for some type of networks.

**Comment by keunwoochoi** [comment]
The question would be about adding new feature vs supporting Theano if they conflict, so it will depend.

**Comment by arijit17** [comment]
Hello!

Thanks for the nice work. 

If I run with CNTK backend, I get this error:
ValueError: CNTK backend: the permute pattern [0, 2, 1] requested permute on dynamic axis, which is not supported. Please do permute on static axis.

This is where this error happens:
x = K.permute_dimensions(x, [0, 2, 1])

Is there any temporary workaround?

**Comment by keunwoochoi** [comment]
Oh, and some unit tests.

**Comment by keunwoochoi** [comment]
Hm, considering to add scattering transform at some point.
