### ISSUE TITLE
When running CNTK with Keras, I'm getting error.

### ISSUE THREAD

**Issue by arijit17** [keunwoochoi/kapre#19]
When running CNTK with Keras, I'm getting this error.
ValueError: CNTK backend: the permute pattern [0, 2, 1] requested permute on dynamic axis, which is not supported. Please do permute on static axis.

This is where this error happens:
x = K.permute_dimensions(x, [0, 2, 1])

Is there any temporary workaround? Any hints how I should change the code?
I tried using:
x = cntk.transpose(x, perm = (0, 2, 1))

**Comment by keunwoochoi** [comment]
Sadly I have no idea how to deal with CNTK backend. During developing I was relying only on Keras backend functions, which are supposed to support all backends and it seems more of Keras issue than Kapre's.

**Comment by arijit17** [comment]
That's true!

It works with TensorFlow backend. 
So, need to wait till the CNTK backend is able to understand permute_dimensions.
