### ISSUE TITLE
Computing the correct spectrogram

### ISSUE THREAD

**Issue by keunwoochoi** [keunwoochoi/kapre#21]
Seems like there's a bug that causes some small difference on the results in the spectrogram. Would anyone be interested in fixing it?

**Comment by lvaleriu** [comment]
Can you add please a python notebook/script which puts this bug in evidence? I'd like to take it.

**Comment by keunwoochoi** [comment]
Great! https://gist.github.com/keunwoochoi/cee596f2c5993110af7d5f2ec5c20129 Here's a short script.

**Comment by Mehdzor** [comment]
How work on this issue is going? I've noticed some inconsistencies aswell.

**Comment by keunwoochoi** [comment]
@Mehdzor I couldn't specify the source of the problem. What kind of inconsistencies did you come up with?

**Comment by Mehdzor** [comment]
Hmm... Checked it again while making a report but now everything is fine. 
I propose covering it with a test, to make sure everything works as intended. Because there is no proof or disproof yet for this issue. And the test will just negate it.

**Comment by keunwoochoi** [comment]
Nice.

Yes, was implementing test cases then realised the error, so can't have test codes before the current problem is fixed..

**Comment by Mehdzor** [comment]
Test case shouldn't depend on the implementation isn't it? Perhaps making an extra-short audio clip and manually converting it to spectrogram might work. By manually I mean a solution based on something failproof like matlab or anything else. 
Hope you got the idea 'cos I'm not an expert.

**Comment by keunwoochoi** [comment]
Oh yeah. To be precise, yes I can have one at the moment; didn’t do it because the current implementation doesn’t pass the test so I didn’t see the point.

On 15 Jan 2018, at 10:56, Maxim Gubin <notifications@github.com<mailto:notifications@github.com>> wrote:
Test case shouldn't depend on theimplementation isn't it? Perhaps making an extra-short audio clip and manually converting it to spectrogram might work. By manually I mean a solution based on something failproof like matlab or anything else.
Hope you got the idea 'cos I'm not an expert.

**Comment by Mehdzor** [comment]
Okay, good to know. Hope the test gets here soon.
P.S. I think your solution should become a standard for audio ML like Keras itself. Very good job.

**Comment by keunwoochoi** [comment]
* pre-multiplying hann windows --> seems fine. tested with rectangular windows but still there's diffs (against librosa stft)
* removed list comprehension and use numpy broadcast instead --> faster computation (during initiating the layer) but results are identical.

**Comment by keunwoochoi** [comment]
fixed in 0.3.
