### ISSUE TITLE
kapre install error

### ISSUE THREAD

**Issue by zzstefan** [keunwoochoi/kapre#22]
Hi，

I installed kapre in two Ubuntu servers. Same problems happened. I don't know what is wrong. 
When I imported kapre in python, erros is down below:

/usr/local/lib/python2.7/dist-packages/llvmlite-0.20.0-py2.7.egg/llvmlite/binding/libllvmlite.so: cannot open shared object file: No such file or directory

I really don't know how to fix this error. I wonder could you please help me solve this error.

**Comment by keunwoochoi** [comment]
LLVM is a compiler and that's all I know, but [googling](https://www.google.com/search?client=safari&rls=en&q=installing+llvm+compiler+ubuntu&ie=UTF-8&oe=UTF-8) will help you.
