### ISSUE TITLE
how to build audio classifier using this?

### ISSUE THREAD

**Issue by StanSilas** [keunwoochoi/kapre#24]
I have  folder containing 100 samples of 1-second long music files. 
When given a an test audio (1-2 minutes long), I want to have a keras model, that will identify where in the audio does the trained music samples occur. 

Please tell me how to achieve this using kapre.

Thank you.

**Comment by keunwoochoi** [comment]
I don’t provide consulting here. Maybe you wanna have a look on dl4mir tutorial.
