### ISSUE TITLE
htk=true for mel frequencies

### ISSUE THREAD

**Issue by justinsalamon** [keunwoochoi/kapre#27]
We noticed the current implenetation of the [mel_frequencies](https://github.com/keunwoochoi/kapre/blob/master/kapre/backend.py#L50) function (based on Librosa) doesn't include the htk=True option, which is handy when training CNNs because then the frequency scale is fully logarithmic which, in principle, makes more sense for frequency invariant convolutional filters.

What was the motivation for removing this? Any chance it can be added?

**Comment by keunwoochoi** [comment]
There's only one reason; to make it simpler as an initial step. PR would be welcomed :)

**Comment by keunwoochoi** [comment]
It will be added -- actually I'll directly use librosa's `mel_frequencies` function instead of relying on copied codes.

**Comment by justinsalamon** [comment]
Has this been added? Can't see it in the code?

**Comment by keunwoochoi** [comment]
Oh, not yet on the master, it's on dev branch only. https://github.com/keunwoochoi/kapre/blob/unittest/kapre/backend.py, sorry to confuse you!

**Comment by justinsalamon** [comment]
Yeah in which case you might want to keep the issue open until the update is merged into master :)

**Comment by keunwoochoi** [comment]
> via commit messages

Oh, didn't know that, interesting!

**Comment by justinsalamon** [comment]
More info: https://help.github.com/articles/closing-issues-using-keywords/
Example of what this looks like from my scaper repo: https://github.com/justinsalamon/scaper/issues/23

**Comment by keunwoochoi** [comment]
Finally, with ver>=0.1.3.
