### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by MHPtbehrens** [keunwoochoi/kapre#31]
Hi there!

I really, really like kapre. Good work!

One thing. I am curious. How well is kapre GPU accelerated? You are using librosa. And to the best of my knowledge, librosa is CPU-only. Could using kapre-layers create bottlenecks when it comes to training time?

Best,
Tristan

**Comment by keunwoochoi** [comment]
Hey, thanks! 
- Librosa is used only when the layers are created. 
- The acceleration is totally dependent on the network size + etc, so it's different for everyone. You can compare the additional computing time by comparing i) a network with Kapre only ii) a network with Kapre + the real deep neural network part. In my case, it's fast enough not to consider alternatives, but it would also depend on how much you'd repeat similar experiments, e.g. if you're gonna do a grid search for 128 different hyperparameters, probably it's worth pre-computing them.
