### ISSUE TITLE
pip package for 0.1.3 broken

### ISSUE THREAD

**Issue by TGabor** [keunwoochoi/kapre#33]
First: thanks for sharing your code! 

I couldn't import kapre after installing it via pip.

Investigating the archive on [pypi](https://pypi.python.org/pypi/kapre) revealed a problem with uppercases in the following filenames:
```
kapre-0.1.3
├── kapre
│   ├── Filterbank.py
│   └── Utils.py
```

Furthermore, the links on pypi to the repo are broken
```
Home Page: http://github.com/keunwoo/kapre/
Download URL: http://github.com/keunwoochoi/kapre/releases
```

**Comment by keunwoochoi** [comment]
* re links: I got it, thanks!
* pypi problem: I also received another email about it, so definitely there's a problem. What's strange is that the `__init__.py` in the current master branch as well as pypi version that you linked specify them with lowercases correctly. I'll need to have a look, but I'm away from home this week and haven't enough time. Do you have any idea?

**Comment by rtjfarrimond** [comment]
Hey both, I am the aforementioned email sender!

I have just edited /usr/local/lib/python2.7/dist-packages/kapre/__init__.py and changed:
filterbank -> Filterbank
utils -> Utils

This has allowed kapre to be imported into my project, though I am yet to do anything with it :)

**Comment by TGabor** [comment]
The problem is in the `kapre-0.1.3.tar.gz` on pypi. For some reasons, the mentioned files are uppercase there. 

I just ran `python setup.py sdist` and the resulting package wasn't having that problem.

On what kind of system did you generate the package in the first place?

**Comment by TGabor** [comment]
@rtjfarrimond I just renamed the files as a quick fix.

**Comment by keunwoochoi** [comment]
It was the same problem as https://github.com/pypa/setuptools/issues/1227 and is now fixed. Thanks for reporting!
