### ISSUE TITLE
TF signal processing?

### ISSUE THREAD

**Issue by tbehrensprivate** [keunwoochoi/kapre#34]
Namaste!

I recently saw, that one of the most recent TensorFlow-releases contains signal processing: 
https://www.tensorflow.org/api_guides/python/contrib.signal

Would it make sense to use this in Kapre? Maybe instead of librosa?

Best,
Tristan

**Comment by keunwoochoi** [comment]
That's nice, also good to know that TF is now more equipped with signal processing modules.
At the moment I'd prefer Kapre to be Keras layers with the backend versatility. But practically many would be using it with TF and it's not very hard to make some layers only available with TF. I'll check it out, although it would take some time (several weeks?) for me to get back to updating Kapre.
