### ISSUE TITLE
Noise layers during training

### ISSUE THREAD

**Issue by tbehrensprivate** [keunwoochoi/kapre#35]
Namaste,

considering the AdditiveNoise-layer:
```
def call(self, x):
        if self.random_gain:
            noise_x = x + K.random_normal(shape=K.shape(x),
                                          mean=0.,
                                          stddev=np.random.uniform(0.0, self.power))
        else:
            noise_x = x + K.random_normal(shape=K.shape(x),
                                          mean=0.,
                                          stddev=self.power)

        return K.in_train_phase(noise_x, x)
```

to me this clearly computes the noise always. That is, during training and not during training. If so, maybe this could be sped up with a function like in Keras? See:
```
def call(self, inputs, training=None):
        if 0 < self.rate < 1:
            def noised():
                stddev = np.sqrt(self.rate / (1.0 - self.rate))
                return inputs * K.random_normal(shape=K.shape(inputs),
                                                mean=1.0,
                                                stddev=stddev)
            return K.in_train_phase(noised, inputs, training=training)
        return inputs
```

Best,
Tristan

**Comment by keunwoochoi** [comment]
Hi, that sounds making sense. 

Could you also explain some other changes for me? What is `self.rate`? Would changing `+` to `*` be beneficial?

**Comment by MHPtbehrens** [comment]
Actually the code snippet is from the Keras Noise-layer: https://github.com/keras-team/keras/blob/master/keras/layers/noise.py

**Comment by keunwoochoi** [comment]
Alright, my code was from the Keras noise layer, which means your suggestion could be better! Overall, I agree with you. It would be nice if you could make an PR, otherwise I'll look into it a bit later.
