### ISSUE TITLE
Input data representation

### ISSUE THREAD

**Issue by slychief** [keunwoochoi/kapre#37]
Hi!

I just wanted to re-check on the input data representation requirements, because I think this is not mentioned in the documentation.

Are the frequency transformation layers expecting integer or float values as input?
According to the provided example, where you use librosa to load the audio data, it should be a float32 representation scaled between -1 and 1.

Is this a fixed requirement or would it also work with int16 values which are returned by scipy.io.wavfile.read()?

Best,
Alex

**Comment by keunwoochoi** [comment]
Right. The current method implicitly expect a normalised float input in [-1, 1]. But it's not a fixed requirement, I think both would work well -- although, of course, the 16-bit integer would result in 2**15 (or 2**15 - 1) times larger STFT magnitudes.
