### ISSUE TITLE
Numba installation warning and subsequent errror

### ISSUE THREAD

**Issue by swang423** [keunwoochoi/kapre#38]
Hi I installed Kapre in Anaconda

The installation has a few warnings about Numba:

Running numba-0.38.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_epmbsvi/numba-0.38.0/egg-dist-tmp-a6780hd_
warning: no files found matching '*.inc' under directory 'numba'
warning: no files found matching '*.ipynb' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/gh-pages'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
zip_safe flag not set; analyzing archive contents...
numba.__pycache__._dispatcher.cpython-34: module references __file__
numba.__pycache__._dynfunc.cpython-34: module references __file__
numba.__pycache__._helperlib.cpython-34: module references __file__
numba.__pycache__.caching.cpython-34: module MAY be using inspect.getsource
numba.__pycache__.errors.cpython-34: module references __file__
numba.__pycache__.mviewbuf.cpython-34: module references __file__
numba.__pycache__.six.cpython-34: module references __path__
numba.__pycache__.tracing.cpython-34: module MAY be using inspect.trace
numba.annotations.__pycache__.type_annotations.cpython-34: module references __file__
numba.cuda.cudadrv.__pycache__._extras.cpython-34: module references __file__
numba.cuda.tests.__pycache__.__init__.cpython-34: module references __file__
numba.cuda.tests.cudadrv.__pycache__.__init__.cpython-34: module references __file__
numba.cuda.tests.cudadrv.__pycache__.test_linker.cpython-34: module references __file__
numba.cuda.tests.cudapy.__pycache__.__init__.cpython-34: module references __file__
numba.cuda.tests.cudasim.__pycache__.__init__.cpython-34: module references __file__
numba.cuda.tests.nocuda.__pycache__.__init__.cpython-34: module references __file__
numba.hsa.tests.hsadrv.__pycache__.test_driver.cpython-34: module references __file__
numba.jitclass.__pycache__._box.cpython-34: module references __file__
numba.npyufunc.__pycache__._internal.cpython-34: module references __file__
numba.npyufunc.__pycache__.workqueue.cpython-34: module references __file__
numba.pycc.__pycache__.cc.cpython-34: module references __file__
numba.runtime.__pycache__._nrt_python.cpython-34: module references __file__
numba.scripts.__pycache__.generate_lower_listing.cpython-34: module references __file__
numba.scripts.__pycache__.generate_lower_listing.cpython-34: module MAY be using inspect.getsourcefile
numba.testing.__pycache__.ddt.cpython-34: module MAY be using inspect.getsourcefile
numba.testing.__pycache__.loader.cpython-34: module references __file__
numba.testing.__pycache__.main.cpython-34: module references __file__
numba.tests.__pycache__.__init__.cpython-34: module references __file__
numba.tests.__pycache__.cffi_usecases.cpython-34: module references __file__
numba.tests.__pycache__.ctypes_usecases.cpython-34: module references __file__
numba.tests.__pycache__.test_cfunc.cpython-34: module references __file__
numba.tests.__pycache__.test_dispatcher.cpython-34: module references __file__
numba.tests.__pycache__.test_pycc.cpython-34: module references __file__
numba.tests.__pycache__.test_stencils.cpython-34: module MAY be using inspect.getsource
numba.tests.npyufunc.__pycache__.__init__.cpython-34: module references __file__
numba.tests.npyufunc.__pycache__.test_caching.cpython-34: module references __file__
numba.typeconv.__pycache__._typeconv.cpython-34: module references __file__
creating /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/numba-0.38.0-py3.4-linux-x86_64.egg
Extracting numba-0.38.0-py3.4-linux-x86_64.egg to /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages
Adding numba 0.38.0 to easy-install.pth file
Installing pycc script to /gruntdata/sicheng.wang/anaconda3/envs/keras/bin
Installing numba script to /gruntdata/sicheng.wang/anaconda3/envs/keras/bin

After installing, importing kapre results in the following error (may be unrelated):

Traceback (most recent call last):
  File "/gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/ffi.py", line 119, in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
  File "/gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/libllvmlite.so: cannot open shared object file: No such file or directory

conda install lvmlite only updates the packets to 0.20.0. Manual compilation of libllvmlite has this error:undefined symbol: LLVMInitializeInstCombine

**Comment by keunwoochoi** [comment]
Hi, sorry for a delayed response. Have you had any update on it? I’m not used to Anaconda or Numba myself and don’t really understand what kinds of problem you had.

On 28 May 2018, at 16:45, swang423 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi I installed Kapre in Anaconda

The installation has a few warnings about Numba:

Running numba-0.38.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-epmbsvi/numba-0.38.0/egg-dist-tmp-a6780hd
warning: no files found matching '.inc' under directory 'numba'
warning: no files found matching '.ipynb' under directory 'docs'
warning: no files found matching '*.txt' under directory 'docs'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/gh-pages'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
zip_safe flag not set; analyzing archive contents...
numba.pycache._dispatcher.cpython-34: module references file
numba.pycache._dynfunc.cpython-34: module references file
numba.pycache._helperlib.cpython-34: module references file
numba.pycache.caching.cpython-34: module MAY be using inspect.getsource
numba.pycache.errors.cpython-34: module references file
numba.pycache.mviewbuf.cpython-34: module references file
numba.pycache.six.cpython-34: module references path
numba.pycache.tracing.cpython-34: module MAY be using inspect.trace
numba.annotations.pycache.type_annotations.cpython-34: module references file
numba.cuda.cudadrv.pycache._extras.cpython-34: module references file
numba.cuda.tests.pycache.init.cpython-34: module references file
numba.cuda.tests.cudadrv.pycache.init.cpython-34: module references file
numba.cuda.tests.cudadrv.pycache.test_linker.cpython-34: module references file
numba.cuda.tests.cudapy.pycache.init.cpython-34: module references file
numba.cuda.tests.cudasim.pycache.init.cpython-34: module references file
numba.cuda.tests.nocuda.pycache.init.cpython-34: module references file
numba.hsa.tests.hsadrv.pycache.test_driver.cpython-34: module references file
numba.jitclass.pycache._box.cpython-34: module references file
numba.npyufunc.pycache._internal.cpython-34: module references file
numba.npyufunc.pycache.workqueue.cpython-34: module references file
numba.pycc.pycache.cc.cpython-34: module references file
numba.runtime.pycache._nrt_python.cpython-34: module references file
numba.scripts.pycache.generate_lower_listing.cpython-34: module references file
numba.scripts.pycache.generate_lower_listing.cpython-34: module MAY be using inspect.getsourcefile
numba.testing.pycache.ddt.cpython-34: module MAY be using inspect.getsourcefile
numba.testing.pycache.loader.cpython-34: module references file
numba.testing.pycache.main.cpython-34: module references file
numba.tests.pycache.init.cpython-34: module references file
numba.tests.pycache.cffi_usecases.cpython-34: module references file
numba.tests.pycache.ctypes_usecases.cpython-34: module references file
numba.tests.pycache.test_cfunc.cpython-34: module references file
numba.tests.pycache.test_dispatcher.cpython-34: module references file
numba.tests.pycache.test_pycc.cpython-34: module references file
numba.tests.pycache.test_stencils.cpython-34: module MAY be using inspect.getsource
numba.tests.npyufunc.pycache.init.cpython-34: module references file
numba.tests.npyufunc.pycache.test_caching.cpython-34: module references file
numba.typeconv.pycache._typeconv.cpython-34: module references file
creating /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/numba-0.38.0-py3.4-linux-x86_64.egg<http://sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/numba-0.38.0-py3.4-linux-x86_64.egg>
Extracting numba-0.38.0-py3.4-linux-x86_64.egg to /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages<http://sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages>
Adding numba 0.38.0 to easy-install.pth file
Installing pycc script to /gruntdata/sicheng.wang/anaconda3/envs/keras/bin<http://sicheng.wang/anaconda3/envs/keras/bin>
Installing numba script to /gruntdata/sicheng.wang/anaconda3/envs/keras/bin<http://sicheng.wang/anaconda3/envs/keras/bin>

After installing, importing kapre results in the following error (may be unrelated):

Traceback (most recent call last):
File "/gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/ffi.py<http://sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/ffi.py>", line 119, in
lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
File "/gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/ctypes/<http://sicheng.wang/anaconda3/envs/keras/lib/python3.4/ctypes/>init.py", line 351, in init
self._handle = _dlopen(self._name, mode)
OSError: /gruntdata/sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/libllvmlite.so:<http://sicheng.wang/anaconda3/envs/keras/lib/python3.4/site-packages/llvmlite-0.23.0-py3.4.egg/llvmlite/binding/libllvmlite.so:> cannot open shared object file: No such file or directory

conda install lvmlite only updates the packets to 0.20.0. Manual compilation of libllvmlite has this error:undefined symbol: LLVMInitializeInstCombine
