### ISSUE TITLE
Any plan to support audio data augmentation?

### ISSUE THREAD

**Issue by liuslevis** [keunwoochoi/kapre#39]
If not, i'm gonna get started doing it : )

**Comment by keunwoochoi** [comment]
Hi, that would be great! Nothing is planed at the moment.

**Comment by liuslevis** [comment]
I'm reading an audio augmentation method [VTLP Jaitly & Hinton 2013].
I'll try that first.

**Comment by usamaehsan** [comment]
Any progress?

**Comment by usamaehsan** [comment]
@liuslevis
