### ISSUE TITLE
trainable_stft error

### ISSUE THREAD

**Issue by sildeag** [keunwoochoi/kapre#4]
Following your example but missing layer definition `trainable_stft` or something, can you provide example with error resolution?
```
`# 6 channels (!), maybe 1-sec audio signal
input_shape = (6, 44100) 
sr = 44100
model = Sequential()
model.add(Melspectrogram(n_dft=512, n_hop=256, input_shape=src_shape,
                         border_mode='same', sr=sr, n_mels=128,
                         fmin=0.0, fmax=sr/2, power=1.0,
                         return_decibel=False, trainable_fb=False,
                         trainable_kernel=False
                         name='trainable_stft'))`

  File "<ipython-input-24-cea5588ddf1e>", line 13
    name='trainable_stft'))
       ^
SyntaxError: invalid syntax
```

**Comment by keunwoochoi** [comment]
Is it from my documentation? Anyway, there's a comma omitted before 'name'.

**Comment by sildeag** [comment]
Hi,

Thanks for getting back.  It is from your documentation.  A comma was 
missing.  There are other issues now so I'll have to isolate them.  I 
was particularly interested in audio examples.

**Comment by keunwoochoi** [comment]
Yeah good. What are the other issues? Please share them with me so that I can fix them!

**Comment by keunwoochoi** [comment]
Could you rely on [this notebook](https://github.com/keunwoochoi/kapre/blob/master/examples/example_codes.ipynb) than the code snippet in `README.md`? They are just snippet, not a fully-working code.

**Comment by sildeag** [comment]
Using your notebook example, which I like, "# Stft" has issue:

Output:
`Keras version: 1.2.2`
`Keras backend: tensorflow`
`Keras image dim ordering: tf`
`Kapre version: 0.0.3`

`---------------------------------------------------------------------------
AsTensorError                             Traceback (most recent call last)
<ipython-input-17-8c7683208372> in <module>()
     14 model = Sequential()
     15 model.add(Stft(n_fft=256, n_hop=64, return_decibel_stft=True,
---> 16               input_shape=src.shape))
     17 model.summary(line_length=80, positions=[.33, .65, .8, 1.])

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in add(self, layer)
    297                 else:
    298                     input_dtype = None
--> 299                 layer.create_input_layer(batch_input_shape, input_dtype)
    300 
    301             if len(layer.inbound_nodes) != 1:

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in create_input_layer(self, batch_input_shape, input_dtype, name)
    399         # and create the node connecting the current layer
    400         # to the input layer we just created.
--> 401         self(x)
    402 
    403     def add_weight(self, shape, initializer, name=None,

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __call__(self, x, mask)
    570         if inbound_layers:
    571             # This will call layer.build() if necessary.
--> 572             self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
    573             # Outputs were already computed when calling self.add_inbound_node.
    574             outputs = self.inbound_nodes[-1].output_tensors

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    633         # creating the node automatically updates self.inbound_nodes
    634         # as well as outbound_nodes on inbound layers.
--> 635         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    636 
    637     def get_output_shape_for(self, input_shape):

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    164 
    165         if len(input_tensors) == 1:
--> 166             output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
    167             output_masks = to_list(outbound_layer.compute_mask(input_tensors[0], input_masks[0]))
    168             # TODO: try to auto-infer shape

/usr/local/lib/python2.7/dist-packages/kapre-0.0.3-py2.7.egg/kapre/stft.pyc in call(self, x, mask)
    139             X_frame_power = K.sum(K.square(fft.rfft(
    140                                         self.fft_window * x[:, :, fr_idx * self.n_hop :
--> 141                                                            fr_idx * self.n_hop + self.n_fft]
    142                                     )), axis=3, keepdims=True)
    143             if fr_idx == 0:

/home/sildeag/audio_detection/Theano/theano/tensor/fft.py in rfft(inp, norm)
    148         scaling = T.sqrt(s.prod().astype(inp.dtype))
    149 
--> 150     return rfft_op(inp, s) / scaling
    151 
    152 

/home/sildeag/audio_detection/Theano/theano/gof/op.pyc in __call__(self, *inputs, **kwargs)
    613         """
    614         return_list = kwargs.pop('return_list', False)
--> 615         node = self.make_node(*inputs, **kwargs)
    616 
    617         if config.compute_test_value != 'off':

/home/sildeag/audio_detection/Theano/theano/tensor/fft.py in make_node(self, a, s)
     16 
     17     def make_node(self, a, s=None):
---> 18         a = T.as_tensor_variable(a)
     19         if a.ndim < 2:
     20             raise TypeError('%s: input must have dimension > 2, with first dimension batches' %

/home/sildeag/audio_detection/Theano/theano/tensor/basic.pyc in as_tensor_variable(x, name, ndim)
    210         except Exception:
    211             str_x = repr(x)
--> 212         raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
    213 
    214 # this has a different name, because _as_tensor_variable is the

AsTensorError: ('Cannot convert Tensor("mul_10:0", shape=(?, 2, 256), dtype=float32) to TensorType', <class 'tensorflow.python.framework.ops.Tensor'>)`

**Comment by keunwoochoi** [comment]
Alright... `Stft` is still somehow unstable. Will take a look later, probably it's tensorflow version difference. I tested it with tf version 0.12.0 on mac, just to let you know.
