### ISSUE TITLE
does this module has 1d Melspectrogram or 2d Melspectrogram?

### ISSUE THREAD

**Issue by NemoCpp** [keunwoochoi/kapre#41]
Hi author
does this module has 1d Melspectrogram or 2d Melspectrogram?

**Comment by keunwoochoi** [comment]
Hi, what do you mean by 1d melspectrogram?

**Comment by NemoCpp** [comment]
like librosa.feature.delta

**Comment by keunwoochoi** [comment]
- AFAIK there's no such thing like 1d melspectrogram.
- librosa.feature.delta is a module to *compute* time-derivative (aka delta) of any 2d representation, which results in 2d as well.

**Comment by NemoCpp** [comment]
in some research, the authors will take melspectrogram, 1d, 2d as three channels of a image like RGB, then apply CNN on it.

**Comment by keunwoochoi** [comment]
I’m one of those authors but 
- it’s not librosa.feature.delta
- there’s no 1d melspectrogram.

Please google more, thanks.

**Comment by NemoCpp** [comment]
thanks
https://blogs.technet.microsoft.com/machinelearning/2018/01/30/hearing-ai-getting-started-with-deep-learning-for-audio-on-azure/
