### ISSUE TITLE
Conversion to Core ML

### ISSUE THREAD

**Issue by XReyRobert-IBM** [keunwoochoi/kapre#43]
Hi all,

I've tryed to convert this to coreml but failed so far...
I tried 2 approches : 
    * kapre / Keras -> coremltools  = FAILED
    * Kapre / Keras -> Tensorflow -> tf-coreml  = FAILED 

Hints anyone ?

**Comment by keunwoochoi** [comment]
Hi, thanks for your interests! I should've reviewed the PR as well.. 
Unfortunately I have no experience on coreml. I can only guess that Kapre shouldn't be a bottleneck on it since, as you probably knew already, there's no twist but only simple keras backend functions. Do you have any idea why it might be not working?

**Comment by XReyRobert-IBM** [comment]
Thanks for your answer, 
I've good hope in the second approach where the model is first being converted to a tensorflow model before being converted to coreml. 
I think I'm running into limitations of tf-coreml, at the moment I think the partial implementation of the transpose operator might be the issue... I'm still investigating...

![output](https://user-images.githubusercontent.com/43029233/47574585-367b8880-d940-11e8-80b7-1f2c2b67c0b9.png)

**Comment by XReyRobert-IBM** [comment]
Could you explain a bit the difference between this implementation and kapre ? I understand this is using directly the "Signal Processing"  to compute the mel spectrogram ?

**Comment by keunwoochoi** [comment]
What we get with them as a result would be pretty much the same. But the implementation above is, yes, based on tensorflow's STFT - so it'd be probably faster (while Kapre is based on the conv layer). Of course it can be used only if you're using tensorflow.
