### ISSUE TITLE
Test PyPI package for 0.1.3.1 still broken

### ISSUE THREAD

**Issue by jtcramer** [keunwoochoi/kapre#44]
Though the fix introduced in 0.1.3.1 has been incorporated in the main PyPI index, the fix is not present in the Test PyPI index, which can be verified by looking at the files in the archive: https://test.pypi.org/project/kapre/#files. This is not an issue for production code, but when testing PyPI packages that depend on kapre, since (AFAIK) even if specifying `--index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple`, pip will still look at the test index first. Since there is indeed a version 0.1.3.1 on Test PyPI, it pulls this version without the fix.

**Comment by keunwoochoi** [comment]
Hey, thanks for such a detail. Actually I'm not very deeply aware of the issue itself. Could you let me know what I should do to fix the situation?

**Comment by keunwoochoi** [comment]
Oh, now I see what you mean. Yes I will, thanks for letting me know!

**Comment by keunwoochoi** [comment]
Solved with version 0.1.4.
