### ISSUE TITLE
Compatibility with Keras2

### ISSUE THREAD

**Issue by lvaleriu** [keunwoochoi/kapre#5]
Hello! I pretty much suppose that you are aware of the current Keras Api changes. Would it be ok for you to support thèse changes? (There are some Breaking changes at the layer implementation). I could submit a PR if that could help you.

**Comment by lvaleriu** [comment]
Just seen that you commited the keras2 transition, so ignore my issue.

**Comment by lvaleriu** [comment]
Just seen that you commited the keras2 transition, so ignore my issue.

**Comment by keunwoochoi** [comment]
:)
