### ISSUE TITLE
Data preperation

### ISSUE THREAD

**Issue by venetisgr** [keunwoochoi/kapre#50]
Hello, is there any specific requirement on how to load our data? I suppose the dimensions have to be (batchesx1xsamples) but is there any specific constraint on the normalization?

**Comment by keunwoochoi** [comment]
Hi, no there's not.

**Comment by keunwoochoi** [comment]
Hi, normalization layers expect the input data shape as STFT or melspectrogram layers output. So it depends on `channel_first` or `channel_last` setup of Keras.
