### ISSUE TITLE
"channels_first" vs "channels_last" parameter for the input

### ISSUE THREAD

**Issue by aelimame** [keunwoochoi/kapre#53]
Hi,

Thank you for the excellent library, it is really very handy.

I have a minor issue related to the fact that the "image_data_format" is only applicable to the output format. I think it would be better if this parameter applies to both the input and the output. Is it possible to change this so if we choose channels_last as a configuration, the input should also be shaped like the output, so something like (samples, n_channels).
I would change the parameter to a Boolean and name it "channels_first" (with a default value to true). Or simply add another parameter for the input, something like "audio_data_format". What do you think?

Thanks!

**Comment by keunwoochoi** [comment]
Hi, thanks :) I'm quite busy these days and wouldn't be able to afford my time to fix it. A PR would be appreciated if one can make one!

**Comment by aelimame** [comment]
Thank you for the quick response :)

Yes I'll see if I can do it in the near future. For the moment I will just make sure the input audio shape is always (n_channels, audio_samples).

Thanks!
