### ISSUE TITLE
Functional API example?

### ISSUE THREAD

**Issue by ArturPrzybysz** [keunwoochoi/kapre#54]
As in title; is it possible to show in examples how to use kapre with keras functional API?

**Comment by ArturPrzybysz** [comment]
I am trying to recreate examples and show any spectrogram. I am getting an info, that 'Spectrogram' is not callable.

Do I have to stick to Sequential model?

**Comment by keunwoochoi** [comment]
Hi, so are there two diff issues? On functional API, I think it should work with it if it worked with Sequential models because that's how Keras Layers work.

**Comment by ArturPrzybysz** [comment]
Actually there's no issue at all. You're right, it works with functional API. The problem was just me believing my IDEs suggestion that Spectrogram is not callable.

Thanks, cool lib!
