### ISSUE TITLE
why magnitute_to_db scale to [-?, 0]

### ISSUE THREAD

**Issue by hackerekcah** [keunwoochoi/kapre#57]
https://github.com/keunwoochoi/kapre/blob/8517f45d3ccb9fff1ec0049b9c3e4389f81c20aa/kapre/backend_keras.py#L23

its different from librosa version:
    if top_db is not None:
        if top_db < 0:
            raise ParameterError('top_db must be non-negative')
        log_spec = np.maximum(log_spec, log_spec.max() - top_db)

I doubts making spectrogram max value to 0 is standard practice.

**Comment by keunwoochoi** [comment]
Hi, it is a design choice. But in the digital domain, quite often the maximum decibel is set to be 0, e.g., in the case of dBFS.
