### ISSUE TITLE
Kapre with something else than tensorflow as Keras backend ?

### ISSUE THREAD

**Issue by XReyRobert** [keunwoochoi/kapre#59]
HI,
I was wondering if it would be possible to run Kapre on keras not using tensorflow as a backend. (Plaidml for example)

**Comment by keunwoochoi** [comment]
Hi, sorry for a late reply - I've been and am on a holiday. Given the situation that Keras' being limited to Tensorflow now, I don't think I can spend time extending it to something else.

**Comment by XReyRobert** [comment]
Right, I was thinking about plaidml but I guess plaidml will be supported by tensorflow via ngraph !
Hard to keep up with changes
