### ISSUE TITLE
kapre in incompatible with keras

### ISSUE THREAD

**Issue by v3551G** [keunwoochoi/kapre#66]
In your demo, Melspectrogram is called with input_shape=(channel, dim), 
While, In my project, 'Input' of keras is used, the default return format is (?, num_channel, num_dim), which denotes baches of num_dim dim vectors with num_channel channels. Next, the return is inputed to Melspectrogram, the error information is:  AttributeError: 'tuple' object has no attribute 'layer', Can you help me to solve this question?
ps: I searched the related topic, the possible reason may be: kapre is dependent on tensorflow.keras, while keras is used to construct model, thus resulting incompatible question.

**Comment by keunwoochoi** [comment]
Hi, I agree that it is probably related to which keras we're using. Since a recent update a a couple of weeks ago. Kapre works on `tensorflow.keras` and does not support the native Keras (which doesn't seem to be supported very actively anymore).
