### ISSUE TITLE
Melspectrogram cant be set 'trainable_fb=False'

### ISSUE THREAD

**Issue by zhh6** [keunwoochoi/kapre#67]
Melspectrogram cant be set 'trainable_fb=False',after  I set trainable_fb=False,trainable_kernel=False,but seems like it doesnot work.It is still trainable.

**Comment by Toku11** [comment]
It's a problem with tf.keras the first solution that comes to mind is to declare MelSpectrogram and set layers as not trainable

model = Sequential()
model.add(Melspectrogram(sr=SR, n_mels=128, 
          n_dft=512, n_hop=128, input_shape=input_shape, 
          return_decibel_melgram=True,
          trainable_kernel=False, name='melgram',trainable_fb=False))
for layer in model.layers:
    layer.trainable = False

**Comment by keunwoochoi** [comment]
@zhh6 Could you provide a test code that checks it like we have in `tests`? I can't spend a lot of time updating `Kapre` these days but can try something small. I guess it'd be fixed if we follow the [new guide](https://www.tensorflow.org/guide/keras/custom_layers_and_models), i.e., something like
```
self.b = self.add_weight(shape=(units,),
                             initializer='zeros',
                             trainable=True)
```

**Comment by zhh6** [comment]
Thanks a lot. I have solved the problem.Just like you do that.
` m = Melspectrogram(sr=SR, n_mels=128, 
          n_dft=512, n_hop=128, input_shape=input_shape, 
          return_decibel_melgram=True,
          trainable_kernel=False, name='melgram',trainable_fb=False)
m.trainble = False`

**Comment by Toku11** [comment]
@keunwoochoi Why not to use only tf.Variable(..., trainable=self.trainable_kernel)
https://github.com/keunwoochoi/kapre/blob/8bf5279ffd12c00ceccdead86df515214d2b5511/kapre/time_frequency.py#L120

I just tried it and it works.

**Comment by Toku11** [comment]
Why not to use only tf.Variable(..,trainable=False) however my question is ...@keunwoochoi  why did you decide to set those variables as "weights" trainable or not? Shouldn't they be fixed?

**Comment by keunwoochoi** [comment]
That's because one might want to set it trainable to optimize the time-frequency representation.

**Comment by keunwoochoi** [comment]
This would be one of the things I'd like to fix wrt `tf2.0` as well as using `tf.stft`. I can also quickly update the code to use `self.add_weight()`, but that should come with stop supporting `tf 1.0` (which I'm fine with).

**Comment by Toku11** [comment]
I'm trying to update using tf.stft ... however I think it's going to be impossible  set kernels as trainable in that scenario... I fact Spectrogram class would be very short... Do you have any idea or recommendation to that update?

**Comment by keunwoochoi** [comment]
that'd be great, thanks! and you're right - with tf.stft, one can't it trainable. 

i just made `https://github.com/keunwoochoi/kapre/tree/kapre-0.2`. this is to aggregate changes towards `kapre 0.2` which would drop tf 1.0 completely. so, for that kind of change, please make a PR to this branch and i'll later merge all of them to `master` at once.
besides, the PR should be just typical - with some unit tests, which we can now compare with librosa.stft :)
