### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer.

### ISSUE THREAD

**Issue by jackz314** [keunwoochoi/kapre#73]
Hi,

I just got started with this library and was following the example [here](https://github.com/keunwoochoi/kapre#one-shot-example), but I'm getting this error:

> TypeError: The added layer must be an instance of class Layer. Found <kapre.time_frequency.Melspectrogram object at 0x000001B7A4077400>

I'm on Windows, with keras version 2.3.1 and TensorFlow version 2.2.0

**Comment by keunwoochoi** [comment]
That's strange. Could you track down a bit more? As you can see on the implementation, `Melspectrogram` is a subclass of keras `Layer`.

**Comment by yuga-k-dj** [comment]
Hi, I'm in the same situation with the Melspectrogram layer, but a little different error:
`TypeError: The added layer must be an instance of class Layer. Found: `

I'm on Mac OS Catalina 10.15.5, with keras version 2.3.1 and TensorFlow version 2.2.0 (the same as former issue).

**Comment by jackz314** [comment]
I just realized what's going on, this error is happening because of the different `keras` code used, in the example, `keras` related things are imported from `keras` whereas in the `kapre` codebase `keras` is actually imported from `tensorflow.keras`. Changing the `keras` import to `tensorflow.keras` fixes the problem.

**Comment by jackz314** [comment]
I made a PR to fix the README at #74.
