### ISSUE TITLE
jypyter run !python  clean.py  only audio file not found for sub string: 3a3d0279 is displayed

### ISSUE THREAD

**Issue by Deep-learning999** [keunwoochoi/kapre#84]
jypyter run !python  clean.py  For the first time, you can generate a clean folder, comment ා split_ After wavs (args), only audio file not found for sub string: 3a3d0279 is displayed

**Comment by Deep-learning999** [comment]
Is this the expected result

**Comment by keunwoochoi** [comment]
I don't think this is related to Kapre. Not sure what it is about..
