### ISSUE TITLE
get_ melspectrogram_ layer  Can replacing melspectrogram get the same output

### ISSUE THREAD

**Issue by Deep-learning999** [keunwoochoi/kapre#85]
i = layers.Input(shape=(1, int(16000*1.0)), name='input')
    x = Melspectrogram(n_dft=512, n_hop=160,
                       padding='same', sr=SR, n_mels=128,
                       fmin=0.0, fmax=SR/2, power_melgram=2.0,
                       return_decibel_melgram=True, trainable_fb=False,
                       trainable_kernel=False,
                       name='melbands')(i)
replacing get_ melspectrogram_ layer  How to change the parameters to get the same output

**Comment by keunwoochoi** [comment]
Hi, I guess you're new to github? It's answered at #82, please go check out and please close this issue once you got it. Thanks!
