### ISSUE TITLE
installing tensorflow , even if tensorflow-gpu aldready installed,

### ISSUE THREAD

**Issue by SacshamAgrawal** [keunwoochoi/kapre#90]
I've been working on tensorflow - gpu, and trying to install kapre for a project, but its installing tensorflow cpu again. Resolve it.

**Comment by keunwoochoi** [comment]
which tensorflow version are you using? after tf2, you're supposed to install tf by `pip install tensorflow` for both cpu and gpu.

**Comment by SacshamAgrawal** [comment]
im using tensorflow/tensorflow:latest-gpu-jupyter docker image
which has 2.3 version

**Comment by keunwoochoi** [comment]
ok but i don't know how i can fix it. maybe in the docker, install `pip install kapre --no-deps` and manually install `numpy` and `librosa` separately?

**Comment by keunwoochoi** [comment]
how did it go?

**Comment by SacshamAgrawal** [comment]
issue can be closed, above solves the problem
