### ISSUE TITLE
Spectrogram details

### ISSUE THREAD

**Issue by v3551G** [keunwoochoi/kapre#97]
kapre.time_frequency.Spectrogram, the output format:(None, n_freq, n_time, n_channel)
The implementation of Spectrogram is based on STFT, of which the outout should in complexity frequency domain. Therefore, I want to know the details of converting the complexity frequency domain to real number domain.

**Comment by keunwoochoi** [comment]
You can use `time_frequency.Magnitude()` layer. You can also try composed layers like https://bytedance.feishu.cn/docs/doccnvYc12F2viZLU2OIaqOIxRg.
